### PR TITLE
Main page - mobile view

### PR DESCRIPTION
**Pull request by IvayloSlavchev**
In this task I have to do mobile/tablet view on the main page. To the current moment I build the UI, but I have to fix the logic in the comments.

### CODE REVIEW

**Review by petya0111 — COMMENTED** [review]
Fix all css values `: end` with `: flex-end` to fix webpack errors

**Comment by IvayloSlavchev** [comment]
> Fix all css values `: end` with `: flex-end` to fix webpack errors
Done

**Review by petya0111 — APPROVED** [review]
Good work, Ivo!

**Comment by di-amond** [comment]
You'll have to fix:
1. The lines between like, comment and share button are darker than the one above them. They should be light.
2. See the stories on the desktop version - the circles come out of the gray rectangle.

**The mobile version IS PERFECT, Ivooooo! Congrats! <3 **

**Comment by IvayloSlavchev** [comment]
> You'll have to fix:
> 
> 1. The lines between like, comment and share button are darker than the one above them. They should be light.
> 2. See the stories on the desktop version - the circles come out of the gray rectangle.
> 
> **The mobile version IS PERFECT, Ivooooo! Congrats! <3 **

Done

**Pull request merged**
