### PR TITLE
added readme

### PR DESCRIPTION
**Pull request by petya0111**
Readme task in Trello https://trello.com/c/tzwWlAn3/43-create-readme-for-the-backend-and-frontend-setup-meet-1302-1d

Here is how it is looking readme, you can suggest new ideas https://github.com/Society-Project/Society/blob/43-create-readme/README.md

### CODE REVIEW

**Comment by azaryan01** [comment]
It looks great. Nice job!

**Review by ghost — APPROVED** [review]
It looks great. Nice job!

**Review by IvayloSlavchev — APPROVED** [review]
Great job, @petya0111! It very simple explained and easy to read! 💪

**Review by cholakovvv — APPROVED** [review]
It looks great. Good job!!

**Review by di-amond — APPROVED** [review]
It is perfect, @petya0111 !!

**Review by PeevG — APPROVED** [review]
Great job, @petya0111 !

**Pull request merged**
