### PR TITLE
Responsive login registration

### PR DESCRIPTION
**Pull request by petya0111**
Login and registration pages task responsiveness
https://trello.com/c/aTkjAnIz/64-login-and-registration-mobile-and-tablet

### CODE REVIEW

**Comment by ZahariCheyrekov** [comment]
Great work, @petya0111! I like the overall appearence of the login and register pages. You can set body `margin: 0` and `margin: 2rem;` to the form wrapper element so the login/register form is correctly positioned on the smaller devices.

**Review by IvayloSlavchev — COMMENTED** [review]
Great job, @petya0111! You did really well. ✅

**Review by IvayloSlavchev — APPROVED** [review]

**Review by di-amond — APPROVED** [review]
Great job, Petya! :gem:

**Review by cholakovvv — APPROVED** [review]
LGTM!

**Pull request merged**
