### PR TITLE
User profile functionality implementation

### PR DESCRIPTION
**Pull request by ZahariCheyrekov**
Readme task in Trello: https://www.figma.com/file/QarG3zw9NTJUzreI9kCbG2/Society-project?node-id=530%3A1039&t=RbwG8g0zhrbM7Ay2-0

Created user profile page, added style to it and created image uploading functionality with Cloudinary.

### CODE REVIEW

**Review by petya0111 — COMMENTED** [review]
The page for the profile is looking good. You can add main sidebars also. Great work!

**Review by cholakovvv — APPROVED** [review]
All looks good. Nice work!

**Review by petya0111 — APPROVED** [review]
Great work with cloudinary, Profile page and implementation!

**Review by IvayloSlavchev — APPROVED** [review]
Great job, @ZahariCheyrekov!

**Review by di-amond — APPROVED** [review]
Good job!

**Pull request merged**
